config/routes.rb
Rails.application.routes.draw do
  devise_for :admin

  namespace :admin do
    root to: "dashboard#index"
    resources :dashboard, only: [:index]
    resources :pages, except: [:show]
    resources :contacts, only: [:index, :show]
    resources :testimonials, except: [:show]
    resources :feature_slides, except: [:show]
  end

  resources :welcome, only: [:index]
  resources :pages, only: [:show]
  resources :contacts, only: [:new, :create]

  root to: "welcome#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :telephone, presence: true
  validates :email, presence: true, format: { with: Devise.email_regexp }
  validates :message, presence: true

  def deliver_email_later
    ContactMailer.notify(self).deliver_later
  end
end

app/models/feature_slide.rb
class FeatureSlide < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId

  friendly_id :title
  has_rich_text :content

  validates :title, presence: true
  validates :slug, presence: true
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  has_rich_text :content

  validates :author, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::BaseController
  def index
    @contacts = Contact.order(created_at: :desc).page params[:paging]
  end

  def show
    @contact = Contact.find(params[:id])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index

  end
end

app/controllers/admin/feature_slides_controller.rb
class Admin::FeatureSlidesController < Admin::BaseController
  before_action :set_slide, only: [:edit, :update, :destroy]

  def index
    @slides = FeatureSlide.order(:title).page params[:paging]
  end

  def new
    @slide = FeatureSlide.new
  end

  def edit
  end

  def create
    @slide = FeatureSlide.new(slide_params)

    if @slide.save
      redirect_to admin_feature_slides_url, notice: 'Slide was successfully created.'
    else
      render :new
    end
  end

  def update
    if @slide.update(slide_params)
      redirect_to admin_feature_slides_url, notice: 'Slide was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @slide.destroy
    redirect_to admin_feature_slides_url, notice: 'Slide was successfully destroyed.'
  end

  private

  def set_slide
    @slide = FeatureSlide.find(params[:id])
  end

  def slide_params
    params.require(:feature_slide).permit(:title, :image)
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
  before_action :set_page, only: [:edit, :update, :destroy]

  def index
    @pages = Page.order(:title).page params[:paging]
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to admin_pages_url, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to admin_pages_url, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_pages_url, notice: 'Page was successfully destroyed.'
  end

  private

  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :meta_title, :meta_description, :content)
  end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < Admin::BaseController
  before_action :set_testimonial, only: [:edit, :update, :destroy]

  def index
    @testimonials = Testimonial.order(created_at: :desc).page params[:paging]
  end

  def new
    @testimonial = Testimonial.new
  end

  def edit
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)

    if @testimonial.save
      redirect_to admin_testimonials_url, notice: 'Testimonial was successfully created.'
    else
      render :new
    end
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to admin_testimonials_url, notice: 'Testimonial was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @testimonial.destroy
    redirect_to admin_testimonials_url, notice: 'Testimonial was successfully destroyed.'
  end

  private

  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end

  def testimonial_params
    params.require(:testimonial).permit(:author, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/base_devise_controller.rb
class BaseDeviseController < ApplicationController
  layout 'admin'
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      @contact.deliver_email_later
      render :create
    else
      return render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :telephone, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @slides = FeatureSlide.order(created_at: :desc)
    @testimonials = Testimonial.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    case controller_name
    when 'pages'
      "Cousins Roofing | #{@page.meta_title || title}"
    when 'contacts'
      'Cousins Roofing | Leave us a message'
    else
      "Cousins Roofing"
    end
  end

  def page_description
    @page&.meta_description || ''
  end

  def page_route(path)
    page_path(path)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/contacts/index.html.erb
<%= render partial: "partials/header", locals: { text: 'Contacts' } %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td class="action">
          <%= link_to admin_contact_path(contact) do %>
            <%= fa_icon "envelope" %> view
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "partials/pagination", locals: { items: @contacts } %>

app/views/admin/contacts/show.html.erb
<%= render partial: "partials/header", locals: { text: "Email from #{@contact.name}" } %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <td><%= @contact.name %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= @contact.email %></td>
  </tr>
  <tr>
    <th>Telephone</th>
    <td><%= @contact.telephone %></td>
  </tr>
  <tr>
    <th>Message</th>
    <td><%= @contact.message %></td>
  </tr>
</table>

<%= link_to 'Back to contacts', admin_contacts_path, class: 'btn btn-primary btn-lg' %>

app/views/admin/dashboard/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= fa_icon "file" %> Pages
        </div>
        <div class="card-body">
          <p class="card-text">Update the content for each of the pages on the website.</p>
          <%= link_to "View Pages", admin_pages_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= fa_icon "image" %> Slides
        </div>
        <div class="card-body">
          <p class="card-text">Administer the featured slides that appear on the homepage.</p>
          <%= link_to "View Slides", admin_feature_slides_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= fa_icon "quote-right" %> Testimonials
        </div>
        <div class="card-body">
          <p class="card-text">Add more testimonials or remove old ones that appear on the website.</p>
          <%= link_to "View Testimonials", admin_testimonials_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= fa_icon "envelope" %> Contacts
        </div>
        <div class="card-body">
          <p class="card-text">View the emails that have been sent by users of the website.</p>
          <%= link_to "View Contacts", admin_contacts_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/feature_slides/edit.html.erb
<%= render partial: "partials/header", locals: { text: "Edit #{@slide.title}" } %>

<%= form_with(model: @slide, local: true, url: admin_feature_slide_path(@slide), method: 'patch') do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @slide } %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Image</label>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <% if @slide.image.attached? %>
    <div class="form-group">
      <label>Current image</label>
      <div class="image-preview">
        <%= image_tag url_for(@slide.image) %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit 'Save slide', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_feature_slides_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/admin/feature_slides/index.html.erb
<%= render partial: "partials/header", locals: { text: 'Slides' } %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.title %></td>
        <td class="action">
          <%= link_to edit_admin_feature_slide_path(slide) do %>
            <%= fa_icon "cog" %> edit
          <% end %>
        </td>
        <td class="action">
          <%= link_to admin_feature_slide_path(slide), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= fa_icon "trash" %> delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "partials/pagination", locals: { items: @slides } %>

<%= link_to 'Create new slide', new_admin_feature_slide_path, class: 'btn btn-primary btn-lg' %>

app/views/admin/feature_slides/new.html.erb
<%= render partial: "partials/header", locals: { text: "Create new slide" } %>

<%= form_with(model: @slide, local: true, url: admin_feature_slides_path) do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @slide } %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Image</label>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create slide', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_feature_slides_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<%= render partial: "partials/header", locals: { text: "Edit #{@page.title}" } %>

<%= form_with(model: @page, local: true, url: admin_page_path(@page), method: 'patch') do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @page } %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Content</label>
    <%= f.rich_text_area :content %>
  </div>

  <div class="form-group">
    <label>Meta title</label>
    <%= f.text_field :meta_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Meta description</label>
    <%= f.text_area :meta_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save page', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_pages_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/admin/pages/index.html.erb
<%= render partial: "partials/header", locals: { text: 'Pages' } %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td class="action">
          <%= link_to edit_admin_page_path(page) do %>
            <%= fa_icon "cog" %> edit
          <% end %>
        </td>
        <td class="action">
          <%= link_to admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= fa_icon "trash" %> delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "partials/pagination", locals: { items: @pages } %>

<%= link_to 'Create new page', new_admin_page_path, class: 'btn btn-primary btn-lg' %>

app/views/admin/pages/new.html.erb
<%= render partial: "partials/header", locals: { text: 'Create new page' } %>

<%= form_with(model: @page, local: true, url: admin_pages_path) do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @page } %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Content</label>
    <%= f.rich_text_area :content %>
  </div>

  <div class="form-group">
    <label>Meta title</label>
    <%= f.text_field :meta_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Meta description</label>
    <%= f.text_area :meta_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create page', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_pages_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/admin/testimonials/edit.html.erb
<%= render partial: "partials/header", locals: { text: "Edit #{@testimonial.title}" } %>

<%= form_with(model: @testimonial, local: true, url: admin_testimonial_path(@testimonial), method: 'patch') do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @testimonial } %>

  <div class="form-group">
    <label>Author</label>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Content</label>
    <%= f.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit 'Save testimonial', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_testimonials_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/admin/testimonials/index.html.erb
<%= render partial: "partials/header", locals: { text: 'Testimonials' } %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Author</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.author %></td>
        <td class="action">
          <%= link_to edit_admin_testimonial_path(testimonial) do %>
            <%= fa_icon "cog" %> edit
          <% end %>
        </td>
        <td class="action">
          <%= link_to admin_testimonial_path(testimonial), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= fa_icon "trash" %> delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "partials/pagination", locals: { items: @testimonials } %>

<%= link_to 'Create new testimonial', new_admin_testimonial_path, class: 'btn btn-primary btn-lg' %>

app/views/admin/testimonials/new.html.erb
<%= render partial: "partials/header", locals: { text: "New testimonial" } %>

<%= form_with(model: @testimonial, local: true, url: admin_testimonials_path) do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @testimonial } %>

  <div class="form-group">
    <label>Author</label>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>Content</label>
    <%= f.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit 'Create testimonial', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', admin_testimonials_path, class: 'btn btn-lg btn-secondary' %>
  </div>
<% end %>

app/views/contacts/create.html.erb
<%= render partial: 'partials/internal_header', locals: { title: 'Thank you' } %>

<div class="cms-content">
  <div class="inner">
    <div class="cms-content-wrapper">
      <p>If you would like a FREE no obligation quote then please leave us a message via our contact form or you can</p>
      <p>Call us on: <a href="tel:07774324872"><strong>07774 324872</strong></a></p>
      <p>Email us at: <a href="mailto:info@cousinsroofing.co.uk"><strong>info@cousinsroofing.co.uk</strong></a></p>
    </div>
  </div>
</div>
<div class="grey-arrow"></div>
<div class="contact-form">
  <div class="inner">
    <div class="contact-form-wrapper">
      <h3>Thank you for your message, we will be in contact shortly.</h3>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render partial: 'partials/internal_header', locals: { title: 'Contact Us' } %>

<div class="cms-content">
  <div class="inner">
    <div class="cms-content-wrapper">
      <p>If you would like a FREE no obligation quote then please leave us a message via our contact form or you can</p>
      <p>Call us on: <a href="tel:07774324872"><strong>07774 324872</strong></a></p>
      <p>Email us at: <a href="mailto:info@cousinsroofing.co.uk"><strong>info@cousinsroofing.co.uk</strong></a></p>
    </div>
  </div>
</div>
<div class="grey-arrow"></div>
<div class="contact-form">
  <div class="inner">
    <div class="contact-form-wrapper">
      <h3>Hello! Please fill in our contact form and we'll be in touch asap.</h3>
      <%= render partial: 'partials/errors', locals: { object: @contact } %>
      <%= form_with model: @contact, local: true do |f| %>
        <div class="form-row form-row-multiple">
          <div class="form-field">
            <label>Name</label>
            <%= f.text_field :name %>
          </div>
          <div class="form-field">
            <label>Telephone</label>
            <%= f.telephone_field :telephone %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-field">
            <label>Email</label>
            <%= f.email_field :email %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-field">
            <label>Your Message</label>
            <%= f.text_area :message %>
          </div>
        </div>
        <div class="form-row">
          <p>Your details will only be used by Cousins Roofing to contact you regarding your query and will not be shared with third parties</p>
        </div>
        <div class="form-row">
          <%= f.submit "Send Enquiry", class: 'button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "admin-styles", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "admin-bundle", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <%= link_to "Dashboard", admin_root_path, class: "navbar-link navbar-brand col-sm-3 col-md-2 mr-0" %>
      <%= link_to("Log out", destroy_admin_session_path, method: :delete, class: "navbar-link navbar-logout") if admin_signed_in? %>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <%= render partial: 'partials/admin_sidebar' if admin_signed_in? %>
          </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <%= render "partials/flash_messages" %>
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="">

  <head>
    <meta charset="utf-8">
    <title><%= page_title %></title>
    <meta name="description" content="<%= page_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="icon.png">
    <link href="https://fonts.googleapis.com/css?family=Quattrocento+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag "styles", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "bundle", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div class="wrapper">
      <div class="header">
        <div class="inner">
          <div class="logo">
            <%= link_to content_tag(:h1, 'Cousins Roofing'), root_path %>
          </div>
          <div class="info">
            <span>
              <a href="mailto:info@cousinsroofing.co.uk">
                <%= fa_icon "envelope" %><span>info@cousinsroofing.co.uk</span>
              </a>
            </span>
            <span>
              <a href="tel:07774324872">
                <%= fa_icon "phone" %></i><span>07774 324872</span>
              </a>
            </span>
            <span class="mobile-menu">
              <a href="#">
                <%= fa_icon "bars" %>
              </a>
            </span>
          </div>
          <div class="navigation">
            <%= fa_icon "times", class: 'mobile-close' %>
            <ul>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Tiling', page_route('tiling') %></li>
              <li><%= link_to 'Slating', page_route('slating') %></li>
              <li><%= link_to 'Leadwork', page_route('leadword') %></li>
              <li><%= link_to 'Velux Windows', page_route('velux-windows') %></li>
              <li><%= link_to 'Testimonials', page_route('testimonials') %></li>
              <li><%= link_to 'Contact', new_contact_path %></li>
            </ul>
          </div>
        </div>
      </div>
      <%= yield %>
      <div class="footer">
        <div class="inner">
          <div class="footer-block footer-about-us">
            <h4>About us</h4>
            <p>Cousins Roofing is a leading Buckinghamshire based family run business with a broad range of expertise in all aspects of roofing services. No job is too big or too small.</p>
          </div>
          <div class="footer-right">
            <div class="footer-block footer-services">
              <h4>Services</h4>
              <ul>
                <li><%= link_to 'Tiling', page_route('tiling') %><a href="#"></a></li>
                <li><%= link_to 'Slating', page_route('slating') %><a href="#"></a></li>
                <li><%= link_to 'Leadwork', page_route('leadwork') %><a href="#"></a></li>
                <li><%= link_to 'Velux Windows', page_route('velux-windows') %><a href="#"></a></li>
                <li><%= link_to 'Chimney re-pointing', page_route('chimney-re-pointing') %><a href="#"></a></li>
                <li><%= link_to 'Ridge, valley & hip repairs', page_route('ridge-valley-hip-repairs') %><a href="#"></a></li>
              </ul>
            </div>
            <div class="footer-block footer-contact-us">
              <h4>Contact us</h4>
              <p>
                <strong>Tel No</strong>
                07774 324872
              </p>
              <p>
                <strong>Email</strong>
                <a href="mailto:cousinsdale@hotmail.com">cousinsdale@hotmail.com</a>
              </p>
              <div class="contact-links">
                <%= link_to 'Get a free quote', new_contact_path, class: 'button free-quote' %>
                <a href="#" class="facebook"><%= image_pack_tag 'media/images/facebook.png', alt: 'Facebook' %></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="design-footer">
        <div class="inner">
          <p>Website by <span>Kayode</span>sign</p>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag "main", 'data-turbolinks-track': "reload" %>
  </body>
</html>

app/views/partials/_admin_sidebar.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <%= link_to admin_root_path, class: "nav-link" do %>
      <%= fa_icon "columns" %>
      <%= content_tag(:span, "Dashboard") %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_pages_path, class: "nav-link" do %>
      <%= fa_icon "file" %>
      <%= content_tag(:span, "Pages") %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_feature_slides_path, class: "nav-link" do %>
      <%= fa_icon "image" %>
      <%= content_tag(:span, "Slides") %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_testimonials_path, class: "nav-link" do %>
      <%= fa_icon "quote-right" %>
      <%= content_tag(:span, "Testimonials") %>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_contacts_path, class: "nav-link" do %>
      <%= fa_icon "envelope" %>
      <%= content_tag(:span, "Contacts") %>
    <% end %>
  </li>
</ul>

app/views/partials/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger form-alert" role="alert">
    <p><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_flash_messages.html.erb
<% flash.each do |alert_type, message| %>
  <div class="alert alert-<%= alert_type %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= message %>
  </div>
<% end %>

app/views/partials/_header.html.erb
<div class="display-header-container">
  <h1 class="display-4"><%= text %></h1>
</div>

app/views/partials/_internal_header.html.erb
<div class="internal-header">
  <div class="inner">
    <%= content_tag(:h2, title) %>
  </div>
</div>

app/views/partials/_pagination.html.erb
<div class="pagination-container">
  <div class="pagination-info"><%= page_entries_info items %></div>
  <%= paginate items, views_prefix: 'partials' %>
</div>